networks:
  dev:
    driver: bridge

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./www:${PROJECT_DIR}
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_fpm
    networks:
      - dev

  php_fpm:
    build:
      context: ./php-fpm
    hostname: fpm.container
    container_name: fpm
    volumes:
      - ./www:${PROJECT_DIR}
    ports:
      - "9000:9000"
    depends_on:
      - redis
    networks:
      - dev

  redis:
    image: redis:alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    hostname: redis.container
    container_name: redis
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - dev

  npm:
    image: node:alpine
    container_name: npm
    volumes:
      - ./www:${PROJECT_DIR}
    working_dir: ${PROJECT_DIR}
    entrypoint: [ 'npm' ]

  composer:
    image: composer:2
    container_name: composer
    volumes:
      - ./www:${PROJECT_DIR}
    depends_on:
      - php_fpm
    networks:
      - dev
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
